# Generated by Django 5.1.3 on 2025-08-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
