# Generated by Django 5.1.3 on 2025-08-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_report_admin_feedback_task_admin_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
