# Generated by Django 5.2.4 on 2025-08-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userbadge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='issuepost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Issue Post', 'verbose_name_plural': 'Issue Posts'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issuepost',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuepost',
            name='location_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='issuepost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='issuepost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-timestamp'], name='core_commen_timesta_7b9dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='issuepost',
            index=models.Index(fields=['-created_at'], name='core_issuep_created_76e69f_idx'),
        ),
        migrations.AddIndex(
            model_name='issuepost',
            index=models.Index(fields=['status'], name='core_issuep_status_74d2b2_idx'),
        ),
        migrations.AddIndex(
            model_name='issuepost',
            index=models.Index(fields=['area'], name='core_issuep_area_200330_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['-timestamp'], name='core_like_timesta_f8953c_idx'),
        ),
    ]
