# Generated by Django 5.2.4 on 2025-08-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_comment_options_alter_issuepost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuepost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
