# Generated by Django 5.2.4 on 2025-08-09 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_savedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemption',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='redemption',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='redemption',
            name='status',
        ),
        migrations.AddField(
            model_name='redemption',
            name='redeemed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='redemption',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StoreOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_offers/')),
                ('coins_required', models.PositiveIntegerField()),
                ('offer_type', models.CharField(choices=[('shop_offer', 'Shop Offer'), ('donor_gift', 'Donor Gift'), ('event_ticket', 'Event Ticket'), ('eco_reward', 'Eco Reward')], max_length=20)),
                ('location_name', models.CharField(max_length=255)),
                ('location_map_url', models.URLField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='redemption',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.storeoffer'),
        ),
    ]
