# Generated by Django 5.2.4 on 2025-08-09 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_redemption_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redemption',
            name='offer',
        ),
        migrations.RenameField(
            model_name='redemption',
            old_name='redeemed_at',
            new_name='requested_at',
        ),
        migrations.RemoveField(
            model_name='redemption',
            name='voucher_code',
        ),
        migrations.AddField(
            model_name='redemption',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='redemption',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='coins_spent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StoreOffer',
        ),
    ]
