# Generated by Django 5.1.3 on 2025-08-10 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_redemption_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.DeleteModel(
            name='Redemption',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
