# Generated by Django 5.1.3 on 2025-08-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_report_user_delete_redemption_delete_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='eco_coins_awarded',
            new_name='initial_eco_coins',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='total_eco_coins_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='verified_eco_coins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('plastic_bottles', 'Donate 100 Plastic Bottles'), ('public_awareness', 'Public Awareness Campaign'), ('tree_planting', 'Tree Planting Drive'), ('community_cleanup', 'Community Cleanup Event'), ('e_waste_collection', 'E-Waste Collection Drive'), ('water_conservation', 'Water Conservation Initiative'), ('other', 'Other Civic Task')], max_length=50),
        ),
    ]
