# Generated by Django 5.1.3 on 2025-08-10 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_eco_coins_awarded_task_initial_eco_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='template', help_text='Provide details about the task you completed.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, help_text='A short, descriptive title for your task.', max_length=100),
            preserve_default=False,
        ),
    ]
