# Generated by Django 5.1.3 on 2025-08-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_task_description_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Provide details about the task you completed, including location and impact.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('plastic_bottles', 'Donate 100 Plastic Bottles (Recycling)'), ('public_awareness', 'Conduct a Public Awareness Campaign'), ('tree_planting', 'Participate in a Tree Planting Drive'), ('community_cleanup', 'Organize/Join a Community Cleanup Event'), ('e_waste_collection', 'Facilitate E-Waste Collection'), ('water_conservation', 'Implement Water Conservation Initiative'), ('energy_saving', 'Promote Energy Saving Practices'), ('composting', 'Start/Maintain a Composting Project'), ('other', 'Other Approved Civic Task')], max_length=50),
        ),
    ]
