# Generated by Django 5.1.3 on 2025-08-10 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_task_description_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepost',
            name='department',
            field=models.CharField(choices=[('public_works', 'Public Works Department'), ('water_supply', 'Water Supply Department'), ('waste_management', 'Waste Management Department'), ('electricity', 'Electricity Department'), ('health_sanitation', 'Health & Sanitation Department'), ('traffic_transport', 'Traffic & Transport Department'), ('parks_recreation', 'Parks & Recreation Department'), ('other', 'Other')], default=django.utils.timezone.now, help_text='Select the relevant department for this issue.', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issuepost',
            name='location_details',
            field=models.CharField(blank=True, help_text="Specific location details (e.g., 'Near City Park, Sector 10')", max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='issuepost',
            index=models.Index(fields=['department'], name='core_issuep_departm_c1605a_idx'),
        ),
    ]
